// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGO.Data;

#nullable disable

namespace SIGO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803192228_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIGO.Models.Autorizante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Denominacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("PlanificacionId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PlanificacionId")
                        .HasDatabaseName("IX_Autorizantes_PlanificacionId");

                    b.HasIndex("PlanificacionId", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("IX_Autorizantes_PlanificacionId_Tipo_SinNumero")
                        .HasFilter("[Numero] IS NULL");

                    b.HasIndex("PlanificacionId", "Tipo", "Numero")
                        .IsUnique()
                        .HasFilter("[Numero] IS NOT NULL");

                    b.ToTable("Autorizantes");
                });

            modelBuilder.Entity("SIGO.Models.Certificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ObraId", "Numero")
                        .IsUnique();

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("SIGO.Models.CertificadoEstructura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificadoId")
                        .HasColumnType("int");

                    b.Property<int>("EstructuraCostosId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal?>("SubtotalActual")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SubtotalAcumulado")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SubtotalAnterior")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("EstructuraCostosId");

                    b.HasIndex("CertificadoId", "EstructuraCostosId")
                        .IsUnique();

                    b.ToTable("CertificadoEstructuras");
                });

            modelBuilder.Entity("SIGO.Models.DigestPlanificacionEnviado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("CantidadMails")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Anio", "Mes")
                        .IsUnique();

                    b.ToTable("DigestsPlanificacionEnviados");
                });

            modelBuilder.Entity("SIGO.Models.EstructuraCostos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActoAdministrativo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Expediente")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.ToTable("EstructurasCostos");
                });

            modelBuilder.Entity("SIGO.Models.IndiceINDEC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIndice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CuadroReferencia")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FamiliaRecurso")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("IncisoCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("IndiceNormalizado")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIndice")
                        .IsUnique();

                    b.ToTable("IndicesINDEC");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoIndice = "ALBANILERIA",
                            CuadroReferencia = "Cuadro 1.5",
                            FamiliaRecurso = "Albañilería / materiales generales de obra",
                            IncisoCode = "b",
                            IndiceNormalizado = "B) Albañilería"
                        },
                        new
                        {
                            Id = 2,
                            CodigoIndice = "ALQ_CAMION_VOLCADOR",
                            CuadroReferencia = "71240 - 11",
                            FamiliaRecurso = "Alquiler de camión volcador"
                        },
                        new
                        {
                            Id = 3,
                            CodigoIndice = "ALQ_PALA_CARGADORA",
                            CuadroReferencia = "51800 - 11",
                            FamiliaRecurso = "Alquiler de pala cargadora"
                        },
                        new
                        {
                            Id = 4,
                            CodigoIndice = "ALQ_RETROEXCAVADORA",
                            CuadroReferencia = "51800 - 21",
                            FamiliaRecurso = "Alquiler de retroexcavadora"
                        },
                        new
                        {
                            Id = 5,
                            CodigoIndice = "ALUMINIO",
                            CuadroReferencia = "2720 41530-1",
                            FamiliaRecurso = "Aluminio"
                        },
                        new
                        {
                            Id = 6,
                            CodigoIndice = "ANDAMIOS",
                            CuadroReferencia = "Cuadro 1.6",
                            FamiliaRecurso = "Andamios",
                            IncisoCode = "f",
                            IndiceNormalizado = "f) Andamios"
                        },
                        new
                        {
                            Id = 7,
                            CodigoIndice = "BALASTOS",
                            CuadroReferencia = "3150 46539-1",
                            FamiliaRecurso = "Balastos"
                        },
                        new
                        {
                            Id = 8,
                            CodigoIndice = "CAMIONES_CHASIS",
                            FamiliaRecurso = "Camiones y transporte pesado",
                            IncisoCode = "(6)",
                            IndiceNormalizado = "(6) 3410 49115-2"
                        },
                        new
                        {
                            Id = 9,
                            CodigoIndice = "CARP_METAL_HERR",
                            CuadroReferencia = "Cuadro 1.5",
                            FamiliaRecurso = "Carpintería metálica, herrería y señalética física",
                            IncisoCode = "d",
                            IndiceNormalizado = "d) Carpinterías"
                        },
                        new
                        {
                            Id = 10,
                            CodigoIndice = "PVC",
                            CuadroReferencia = "Cuadro 1.9",
                            FamiliaRecurso = "Caños de PVC / plásticos para instalaciones",
                            IncisoCode = "h",
                            IndiceNormalizado = "h) Caños de PVC para instalaciones varias"
                        },
                        new
                        {
                            Id = 11,
                            CodigoIndice = "CAÑO_ACERO_INST_ELECTRICA",
                            CuadroReferencia = "41277 - 21",
                            FamiliaRecurso = "Caños de acero para instalación eléctrica"
                        },
                        new
                        {
                            Id = 12,
                            CodigoIndice = "CEMENTO_CAL",
                            CuadroReferencia = "2694",
                            FamiliaRecurso = "Cemento y cal"
                        },
                        new
                        {
                            Id = 13,
                            CodigoIndice = "CERAMICOS_BALDOSAS",
                            FamiliaRecurso = "Cerámicos, baldosas y losas",
                            IncisoCode = "(1)",
                            IndiceNormalizado = "(1) 37370"
                        },
                        new
                        {
                            Id = 14,
                            CodigoIndice = "CHAPAS_METALICAS",
                            CuadroReferencia = "2899 42999-2",
                            FamiliaRecurso = "Chapas metálicas y productos metálicos elaborados"
                        },
                        new
                        {
                            Id = 15,
                            CodigoIndice = "COMB_LUB",
                            CuadroReferencia = "Cuadro 3.2-23",
                            FamiliaRecurso = "Combustibles, asfaltos y lubricantes",
                            IncisoCode = "k",
                            IndiceNormalizado = "k) Asfaltos, combustibles y lubricantes"
                        },
                        new
                        {
                            Id = 16,
                            CodigoIndice = "ELECTROBOMBA",
                            FamiliaRecurso = "Electrobombas",
                            IncisoCode = "v",
                            IndiceNormalizado = "v) Electrobomba"
                        },
                        new
                        {
                            Id = 17,
                            CodigoIndice = "GASTOS_GENERALES",
                            CuadroReferencia = "Cuadro 1.4",
                            FamiliaRecurso = "Gastos generales / subcontratos / servicios auxiliares",
                            IncisoCode = "p",
                            IndiceNormalizado = "p) Gastos generales"
                        },
                        new
                        {
                            Id = 18,
                            CodigoIndice = "HERRAMIENTAS_MANO",
                            CuadroReferencia = "2893 42921-2",
                            FamiliaRecurso = "Herramientas de mano"
                        },
                        new
                        {
                            Id = 19,
                            CodigoIndice = "HIDROFUGOS",
                            CuadroReferencia = "2699 37990-1",
                            FamiliaRecurso = "Hidrófugos"
                        },
                        new
                        {
                            Id = 20,
                            CodigoIndice = "ACERO_HIERRO",
                            FamiliaRecurso = "Hierros, aceros y perfiles básicos",
                            IncisoCode = "(2)",
                            IndiceNormalizado = "(2) 2710 27101"
                        },
                        new
                        {
                            Id = 21,
                            CodigoIndice = "HORMIGON",
                            CuadroReferencia = "Cuadro 1.9",
                            FamiliaRecurso = "Hormigón elaborado y premoldeados",
                            IncisoCode = "s",
                            IndiceNormalizado = "s) Hormigón"
                        },
                        new
                        {
                            Id = 22,
                            CodigoIndice = "IMPERMEABILIZANTES",
                            CuadroReferencia = "2422 35110-5",
                            FamiliaRecurso = "Impermeabilizantes químicos"
                        },
                        new
                        {
                            Id = 23,
                            CodigoIndice = "INST_ELECTRICA",
                            CuadroReferencia = "Cuadro 1.5",
                            FamiliaRecurso = "Instalación eléctrica, iluminación y cableado",
                            IncisoCode = "g",
                            IndiceNormalizado = "g) Artefactos de iluminación y cableado"
                        },
                        new
                        {
                            Id = 24,
                            CodigoIndice = "SANITARIA_INCENDIO",
                            CuadroReferencia = "Cuadro 1.5",
                            FamiliaRecurso = "Instalación sanitaria y contra incendio",
                            IncisoCode = "r",
                            IndiceNormalizado = "r) Artefactos para baño y grifería"
                        },
                        new
                        {
                            Id = 25,
                            CodigoIndice = "JABALINA",
                            CuadroReferencia = "42999 - 51",
                            FamiliaRecurso = "Jabalinas y puesta a tierra"
                        },
                        new
                        {
                            Id = 26,
                            CodigoIndice = "LADRILLOS",
                            CuadroReferencia = "2693 37350-1",
                            FamiliaRecurso = "Ladrillos y mampuestos cerámicos"
                        },
                        new
                        {
                            Id = 27,
                            CodigoIndice = "MADERA",
                            FamiliaRecurso = "Madera y carpintería de madera",
                            IndiceNormalizado = "Var 8.1.2 Carpintería de madera"
                        },
                        new
                        {
                            Id = 28,
                            CodigoIndice = "MANO_OBRA",
                            CuadroReferencia = "Cuadro 1.4",
                            FamiliaRecurso = "Mano de obra",
                            IncisoCode = "a",
                            IndiceNormalizado = "a) Mano de obra"
                        },
                        new
                        {
                            Id = 29,
                            CodigoIndice = "MEMBRANAS_PLASTICOS",
                            CuadroReferencia = "Cuadro 3.2-252",
                            FamiliaRecurso = "Membranas, impermeabilizantes plásticos y geosintéticos",
                            IncisoCode = "w",
                            IndiceNormalizado = "w) Membrana impermeabilizante / Productos de plástico"
                        },
                        new
                        {
                            Id = 30,
                            CodigoIndice = "MOSAICO_GRANITICO",
                            CuadroReferencia = "37540 - 11",
                            FamiliaRecurso = "Mosaico / granito / marmolería"
                        },
                        new
                        {
                            Id = 31,
                            CodigoIndice = "MOTORES_ELECTRICOS_AA",
                            CuadroReferencia = "Cuadro 3.2-31",
                            FamiliaRecurso = "Motores eléctricos y equipos electromecánicos / AA",
                            IncisoCode = "i",
                            IndiceNormalizado = "i) Motores eléctricos y equipos de aire acondicionado"
                        },
                        new
                        {
                            Id = 32,
                            CodigoIndice = "MAQUINAS_HERRAMIENTAS",
                            CuadroReferencia = "2922 29221",
                            FamiliaRecurso = "Máquinas herramientas y accesorios"
                        },
                        new
                        {
                            Id = 33,
                            CodigoIndice = "PIEDRAS_ARENAS_ARCILLAS",
                            FamiliaRecurso = "Piedras, arenas y arcillas",
                            IncisoCode = "(29)",
                            IndiceNormalizado = "(29) 1410 14101"
                        },
                        new
                        {
                            Id = 34,
                            CodigoIndice = "PINTURA",
                            CuadroReferencia = "51730 - 1",
                            FamiliaRecurso = "Pinturas y solventes"
                        },
                        new
                        {
                            Id = 35,
                            CodigoIndice = "PISOS_REVEST",
                            FamiliaRecurso = "Pisos y revestimientos",
                            IncisoCode = "c",
                            IndiceNormalizado = "c) Pisos y revestimientos"
                        },
                        new
                        {
                            Id = 36,
                            CodigoIndice = "TAPA_CHAPA_CAMARA",
                            CuadroReferencia = "37560 - 21",
                            FamiliaRecurso = "Tapas de chapa para cámaras"
                        },
                        new
                        {
                            Id = 37,
                            CodigoIndice = "VIDRIOS",
                            FamiliaRecurso = "Vidrios, espejos y blindex",
                            IncisoCode = "(21)",
                            IndiceNormalizado = "(21) 2610 26101"
                        },
                        new
                        {
                            Id = 38,
                            CodigoIndice = "VALVULAS_BRONCE",
                            FamiliaRecurso = "Válvulas de bronce",
                            IncisoCode = "u",
                            IndiceNormalizado = "u) Válvulas de bronce"
                        },
                        new
                        {
                            Id = 39,
                            CodigoIndice = "ZOCALO_GRANITICO",
                            CuadroReferencia = "37540 - 21",
                            FamiliaRecurso = "Zócalos graníticos"
                        },
                        new
                        {
                            Id = 40,
                            CodigoIndice = "COSTO_FINANCIERO",
                            FamiliaRecurso = "Costo Financiero – Tasas Activas Banco Nación"
                        });
                });

            modelBuilder.Entity("SIGO.Models.ItemCertificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadActual")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CantidadAcumulada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CantidadAnterior")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CantidadContrato")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CertificadoEstructuraId")
                        .HasColumnType("int");

                    b.Property<int>("ItemEstructuraId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoActual")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MontoAcumulado")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MontoAnterior")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MontoContrato")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("PUBasico")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PorcentajeActual")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("PorcentajeAcumulado")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("PorcentajeAnterior")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ItemEstructuraId");

                    b.HasIndex("CertificadoEstructuraId", "ItemEstructuraId")
                        .IsUnique();

                    b.ToTable("ItemsCertificado");
                });

            modelBuilder.Entity("SIGO.Models.ItemEstructura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgrupadorPadreId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsAgrupador")
                        .HasColumnType("bit");

                    b.Property<int>("EstructuraCostosId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemOrigenId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Monto")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<decimal?>("PUBasico")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Unidad")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AgrupadorPadreId");

                    b.HasIndex("EstructuraCostosId");

                    b.HasIndex("ItemOrigenId");

                    b.ToTable("ItemsEstructura");
                });

            modelBuilder.Entity("SIGO.Models.ItemPonderacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionINDEC")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IndiceId")
                        .HasColumnType("int");

                    b.Property<string>("Insumo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoPorcentaje")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TablaPonderacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndiceId");

                    b.HasIndex("TablaPonderacionId", "Numero")
                        .IsUnique();

                    b.ToTable("ItemsPonderacion");
                });

            modelBuilder.Entity("SIGO.Models.Obra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Antecedentes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Contratista")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CorreoDirectorObra")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DirectorObra")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("DirectorUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAdjudicacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaContrato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalContrato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaOferta")
                        .HasColumnType("datetime2");

                    b.Property<string>("IFActaInicio")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("IFAdjudicacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("IFContrato")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("IFDesignacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NumeroLicitacion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("OfertaFinal")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PUByC")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PlazoObra")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorUsuarioId");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("SIGO.Models.PlanMonto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("AutorizanteId")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AutorizanteId", "Concepto", "Moneda", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("PlanMontos");
                });

            modelBuilder.Entity("SIGO.Models.PlanMontoSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Denominacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("PlanificacionSnapshotId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PlanificacionSnapshotId");

                    b.ToTable("PlanMontoSnapshots");
                });

            modelBuilder.Entity("SIGO.Models.Planificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correcciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaTomaConocimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRevision")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("ObraFinalizada")
                        .HasColumnType("bit");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TomadaConocimientoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ObraId")
                        .IsUnique();

                    b.ToTable("Planificaciones");
                });

            modelBuilder.Entity("SIGO.Models.PlanificacionSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaTomaConocimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<string>("TomadaConocimientoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ObraId", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("PlanificacionSnapshots");
                });

            modelBuilder.Entity("SIGO.Models.RedeterminacionGuardada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioBase")
                        .HasColumnType("int");

                    b.Property<int>("AnioSalto")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaAprobacionCCyR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAprobacionOS")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGuardado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimitePresentacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdPublicacionBase")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("IdPublicacionSalto")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("MesBase")
                        .HasColumnType("int");

                    b.Property<int>("MesSalto")
                        .HasColumnType("int");

                    b.Property<int>("NroDisparo")
                        .HasColumnType("int");

                    b.Property<string>("NroExpedienteVR")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PorcentajeAumento")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TablaPonderacionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalKiK0")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("VariacionAcumulada")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("TablaPonderacionId");

                    b.HasIndex("ObraId", "NroDisparo")
                        .IsUnique();

                    b.ToTable("RedeterminacionesGuardadas");
                });

            modelBuilder.Entity("SIGO.Models.RedeterminacionGuardadaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionINDEC")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IndiceId")
                        .HasColumnType("int");

                    b.Property<string>("Insumo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("ItemPonderacionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("KiK0")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoPorcentaje")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.Property<int>("RedeterminacionGuardadaId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("ValorIndiceBaseId")
                        .HasColumnType("int");

                    b.Property<int?>("ValorIndiceSaltoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorMesBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ValorMesSalto")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("VariacionPonderada")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("IndiceId");

                    b.HasIndex("ItemPonderacionId");

                    b.HasIndex("RedeterminacionGuardadaId");

                    b.HasIndex("ValorIndiceBaseId");

                    b.HasIndex("ValorIndiceSaltoId");

                    b.ToTable("RedeterminacionesGuardadasItems");
                });

            modelBuilder.Entity("SIGO.Models.RolloverPlanificacionEjecutado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("CantidadPlanesReiniciados")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEjecucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Anio", "Mes")
                        .IsUnique();

                    b.ToTable("RolloversPlanificacionEjecutados");
                });

            modelBuilder.Entity("SIGO.Models.TablaPonderacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ObraId")
                        .IsUnique();

                    b.ToTable("TablasPonderacion");
                });

            modelBuilder.Entity("SIGO.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WindowsUser")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("WindowsUser")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SIGO.Models.UsuarioRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Rol")
                        .IsUnique();

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("SIGO.Models.ValorIndice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("IdPublicacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("IndiceId")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("IndiceId", "Anio", "Mes", "IdPublicacion")
                        .IsUnique()
                        .HasFilter("[IdPublicacion] IS NOT NULL");

                    b.HasIndex(new[] { "IndiceId", "Anio", "Mes" }, "IX_ValoresIndice_IndiceId_Anio_Mes");

                    b.HasIndex(new[] { "IndiceId", "Anio", "Mes" }, "IX_ValoresIndice_IndiceId_Anio_Mes_SinPublicacion")
                        .IsUnique()
                        .HasFilter("[IdPublicacion] IS NULL");

                    b.ToTable("ValoresIndice");
                });

            modelBuilder.Entity("SIGO.Models.Autorizante", b =>
                {
                    b.HasOne("SIGO.Models.Planificacion", "Planificacion")
                        .WithMany("Autorizantes")
                        .HasForeignKey("PlanificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planificacion");
                });

            modelBuilder.Entity("SIGO.Models.Certificado", b =>
                {
                    b.HasOne("SIGO.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("SIGO.Models.CertificadoEstructura", b =>
                {
                    b.HasOne("SIGO.Models.Certificado", "Certificado")
                        .WithMany("Estructuras")
                        .HasForeignKey("CertificadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGO.Models.EstructuraCostos", "EstructuraCostos")
                        .WithMany()
                        .HasForeignKey("EstructuraCostosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Certificado");

                    b.Navigation("EstructuraCostos");
                });

            modelBuilder.Entity("SIGO.Models.EstructuraCostos", b =>
                {
                    b.HasOne("SIGO.Models.Obra", "Obra")
                        .WithMany("EstructurasCostos")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("SIGO.Models.ItemCertificado", b =>
                {
                    b.HasOne("SIGO.Models.CertificadoEstructura", "CertificadoEstructura")
                        .WithMany("Items")
                        .HasForeignKey("CertificadoEstructuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGO.Models.ItemEstructura", "ItemEstructura")
                        .WithMany()
                        .HasForeignKey("ItemEstructuraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CertificadoEstructura");

                    b.Navigation("ItemEstructura");
                });

            modelBuilder.Entity("SIGO.Models.ItemEstructura", b =>
                {
                    b.HasOne("SIGO.Models.ItemEstructura", "AgrupadorPadre")
                        .WithMany("Hijos")
                        .HasForeignKey("AgrupadorPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGO.Models.EstructuraCostos", "EstructuraCostos")
                        .WithMany("Items")
                        .HasForeignKey("EstructuraCostosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGO.Models.ItemEstructura", "ItemOrigen")
                        .WithMany()
                        .HasForeignKey("ItemOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AgrupadorPadre");

                    b.Navigation("EstructuraCostos");

                    b.Navigation("ItemOrigen");
                });

            modelBuilder.Entity("SIGO.Models.ItemPonderacion", b =>
                {
                    b.HasOne("SIGO.Models.IndiceINDEC", "Indice")
                        .WithMany()
                        .HasForeignKey("IndiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGO.Models.TablaPonderacion", "TablaPonderacion")
                        .WithMany("Items")
                        .HasForeignKey("TablaPonderacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indice");

                    b.Navigation("TablaPonderacion");
                });

            modelBuilder.Entity("SIGO.Models.Obra", b =>
                {
                    b.HasOne("SIGO.Models.Usuario", "DirectorUsuario")
                        .WithMany()
                        .HasForeignKey("DirectorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DirectorUsuario");
                });

            modelBuilder.Entity("SIGO.Models.PlanMonto", b =>
                {
                    b.HasOne("SIGO.Models.Autorizante", "Autorizante")
                        .WithMany("Montos")
                        .HasForeignKey("AutorizanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autorizante");
                });

            modelBuilder.Entity("SIGO.Models.PlanMontoSnapshot", b =>
                {
                    b.HasOne("SIGO.Models.PlanificacionSnapshot", "Snapshot")
                        .WithMany("Montos")
                        .HasForeignKey("PlanificacionSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("SIGO.Models.Planificacion", b =>
                {
                    b.HasOne("SIGO.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("SIGO.Models.PlanificacionSnapshot", b =>
                {
                    b.HasOne("SIGO.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("SIGO.Models.RedeterminacionGuardada", b =>
                {
                    b.HasOne("SIGO.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGO.Models.TablaPonderacion", "TablaPonderacion")
                        .WithMany()
                        .HasForeignKey("TablaPonderacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("TablaPonderacion");
                });

            modelBuilder.Entity("SIGO.Models.RedeterminacionGuardadaItem", b =>
                {
                    b.HasOne("SIGO.Models.IndiceINDEC", null)
                        .WithMany()
                        .HasForeignKey("IndiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGO.Models.ItemPonderacion", null)
                        .WithMany()
                        .HasForeignKey("ItemPonderacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGO.Models.RedeterminacionGuardada", "Redeterminacion")
                        .WithMany("Items")
                        .HasForeignKey("RedeterminacionGuardadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGO.Models.ValorIndice", null)
                        .WithMany()
                        .HasForeignKey("ValorIndiceBaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGO.Models.ValorIndice", null)
                        .WithMany()
                        .HasForeignKey("ValorIndiceSaltoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Redeterminacion");
                });

            modelBuilder.Entity("SIGO.Models.TablaPonderacion", b =>
                {
                    b.HasOne("SIGO.Models.Obra", "Obra")
                        .WithMany("TablasPonderacion")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("SIGO.Models.UsuarioRol", b =>
                {
                    b.HasOne("SIGO.Models.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGO.Models.ValorIndice", b =>
                {
                    b.HasOne("SIGO.Models.IndiceINDEC", "Indice")
                        .WithMany("Valores")
                        .HasForeignKey("IndiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indice");
                });

            modelBuilder.Entity("SIGO.Models.Autorizante", b =>
                {
                    b.Navigation("Montos");
                });

            modelBuilder.Entity("SIGO.Models.Certificado", b =>
                {
                    b.Navigation("Estructuras");
                });

            modelBuilder.Entity("SIGO.Models.CertificadoEstructura", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SIGO.Models.EstructuraCostos", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SIGO.Models.IndiceINDEC", b =>
                {
                    b.Navigation("Valores");
                });

            modelBuilder.Entity("SIGO.Models.ItemEstructura", b =>
                {
                    b.Navigation("Hijos");
                });

            modelBuilder.Entity("SIGO.Models.Obra", b =>
                {
                    b.Navigation("EstructurasCostos");

                    b.Navigation("TablasPonderacion");
                });

            modelBuilder.Entity("SIGO.Models.Planificacion", b =>
                {
                    b.Navigation("Autorizantes");
                });

            modelBuilder.Entity("SIGO.Models.PlanificacionSnapshot", b =>
                {
                    b.Navigation("Montos");
                });

            modelBuilder.Entity("SIGO.Models.RedeterminacionGuardada", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SIGO.Models.TablaPonderacion", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SIGO.Models.Usuario", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
